<a href="https://colab.research.google.com/github/Pawan-choudhary/Car-Price-Prediction/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#!pip install ipython-autotime
#%load_ext autotime


In [2]:
import numpy as np

In [3]:
a = [1,2,3,4,5]
# Find Squre of each element

In [4]:
#Method 1
a_seq = [element**2 for element in a] # element wise operation
a_seq

[1, 4, 9, 16, 25]

--------------------------------------------------------------------------------
**np.array(list_name) -> convert python list to numpy array/ create numy array**

In [5]:
a_np = np.array(a)
a_np

array([1, 2, 3, 4, 5])

In [6]:
print(a_np)

[1 2 3 4 5]


In [7]:
a_np**2

array([ 1,  4,  9, 16, 25])

In [8]:
l = range(1000000)

In [9]:
len(l)

1000000

In [10]:
%timeit [i**2 for i in l]

321 ms ± 8.28 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


--------------------------------------------------------------------------------
Square using numpy

In [11]:
l_np = np.arange(1000000)

In [12]:
len(l_np)

1000000

In [13]:
%timeit l_np**2

1.59 ms ± 270 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


IF ou have to perform element wise operation numpy provides


1.   clean syntax
2.   Computation Benefit



--------------------------------------------------------------------------------
**np.array(list_name) :create numpy array**

In [14]:
a = np.array([1,2,3])

In [15]:
a*2

array([2, 4, 6])

**.ndim**

In [16]:
a.ndim #Its a property not a function

1

**.shape** : It wil tell number of elements across each and everyday dimension

In [17]:
a.shape # It wil tellnumber of elements across each and everyday dimension

(3,)

output (3,) : Across the first dimension we have 3 elements

In [18]:
a = np.array([1,2,3,4,5,6,7,8])
print("Dimension is :",a.ndim,'and shape is :', a.shape)

Dimension is : 1 and shape is : (8,)


output means : 8 element across the first dimension

--------------------------------------------------------------------------------

In [19]:
a = np.array([1,2,3,4,5,6])
b = len(a)
print(b)

6


----------------------------------------------------------------------------------------------------------------------------------------------

In [20]:
np.arange(1,5)

array([1, 2, 3, 4])

In [21]:
np.arange(1,5,2)

array([1, 3])

In [22]:
np.arange(1,5,0.5) #Float -> valid for arange, not for range

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

**np.arange**(start,end,step size) : can put flaoting point step size. Can't do this in range
* end point is not included


-----------------------------------------------------------------------------------

**np.linspace(start,end,count)** 
* Use when we have to divide range in equal parts
* end point included in .linespace()

In [23]:
# start, end, count(number of elements required)
np.linspace(0,100,12) # end point in inclusive

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

In [24]:
np.linspace(0,100,9)

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [25]:
type(a_np)

numpy.ndarray

**Note :** numpy is written in C language. Thats why its faster and stores homogeneous data type. That's why its called numpy array not numy list


---------------------------------------------------------------------------------

In [26]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [27]:
arr1 = np.array([1,2,3,4.0])
print(arr1)

[1. 2. 3. 4.]


numpy do automaticaly conversion and convert int to float to maintain homoginaty
* Not convert flaot to int otherwise it will loss inforamtion
* To perform specific type conversion, we can use dtype='data type'

In [28]:
np.array([1,2,3,4],dtype='float')


array([1., 2., 3., 4.])

In [29]:
np.array([1,2,3,4,'Pawan'])

array(['1', '2', '3', '4', 'Pawan'], dtype='<U21')

--------------------------------------------------------------------------------

Over Flow problem

In [30]:
100**10

100000000000000000000

In [31]:
arr = np.array([0,10,100])
arr**10

array([                  0,         10000000000, 7766279631452241920])

In [32]:
np.array([0,10,100]).dtype

dtype('int64')

--------------------------------------------------------------------------------

# **Working with 2-D Array**

In [33]:
m1 = np.array([[1,2,3],[4,5,6]])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
m1.ndim

2

In [35]:
m1.shape

(2, 3)

(2,3) : number of elements accross one dim(row) is 2 and other dim(col) is 3 

In [36]:
len(m1)

2

------------------------------------------------------------------------------------------------------------------------------------------

**ndim** : convert 1-D to n-D array

In [37]:
a = np.array([1,2,3,4,5],ndmin=2)
print(a)

[[1 2 3 4 5]]


In [38]:
a.ndim

2

In [39]:
a.shape

(1, 5)

--------------------------------------------------------------------------------

Changing the dimension of numpy array using **.reshape()**

In [40]:
m2 = np.arange(1,13)
print(m2)
print("Dimension :",m2.ndim)
print('shape :',m2.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension : 1
shape : (12,)


In [41]:
m2.reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
m2.reshape(4,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
m2.reshape(12,1)


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [44]:
m2.reshape(2,6)



array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

--------------------------------------------------------------------------------

**np.resize(a,new_shape)** : If the new array is larger than the original array, then the new array is filled with repeated copies of a. Note that this behavior is different from **a.resize(new_shape)** which fills with zeros instead of repeated copies of a.

In [45]:
c = np.arange(4)
c

array([0, 1, 2, 3])

In [46]:
# c.reshape(2,4)  it will give error
# ValueError: cannot reshape array of size 4 into shape (2,4)
np.resize(c,(2,4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [47]:
a = np.arange(4)
a.resize((3,4))
a

array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
b = np.arange(4)
np.resize(b,(2,4))


array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [49]:
c = a

In [50]:
a.resize((3,4))


--------------------------------------------------------------------------------------------

In [51]:
a = np.arange(3)

In [52]:
a

array([0, 1, 2])

In [53]:
a.ndim

1

In [54]:
a.shape

(3,)

In [55]:
a = np.arange(3).reshape(1,3)

In [56]:
a 

array([[0, 1, 2]])

In [57]:
a.ndim

2

In [58]:
a.shape

(1, 3)

In [59]:
a.T  # Transpose


array([[0],
       [1],
       [2]])

In [60]:
a = np.arange(3)
a #this is not a row vactor . row vecotr is always a 2-D object
  # its a 1-D object

array([0, 1, 2])

In [61]:
a.T

array([0, 1, 2])

**NOTE** : Transpose of a 1-D array is itself only

--------------------------------------------------------------------------------

**arr.flatten()**

In [62]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
a.reshape(1,12).ndim

2

In [65]:
a.reshape(12).ndim

1

In [66]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a.reshape(6,-1) # Automaticaly detecting what should be the value at -1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

--------------------------------------------------------------------------------

**np.zeros(shape)**

In [68]:
np.zeros(4)

array([0., 0., 0., 0.])

In [69]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

--------------------------------------------------------------------------------

**np.ones(shape)**

In [70]:
np.ones(4)

array([1., 1., 1., 1.])

In [71]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
np.ones((2,3))*5

array([[5., 5., 5.],
       [5., 5., 5.]])

--------------------------------------------------------------------------------

**np.diag()** : create Diagonal matrix

In [73]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [74]:
# Interview Questions
a = np.diag([1,2,3])
b = np.diag(a)

In [75]:
b

array([1, 2, 3])

--------------------------------------------------------------------------------

**np.identity()**

In [76]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

--------------------------------------------------------------------------------

# Indexing and slicing

In [77]:
m1 = np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
m1[2]   # m1[12] -> IndexError

2

In [79]:
m1[0:5]

array([0, 1, 2, 3, 4])

In [80]:
m1 = np.arange(1,10).reshape(3,3)
print(m1)

#    0 1 2
#  [[1 2 3]  0
#  [4 5 6]   1
#  [7 8 9]]  2

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
m1[1][2] #not use this syntax

6

In [82]:
m1[1,2] # use this syntax

6

In [83]:
# multiple index
m2 = np.array([100,200,300,400,500,600])
m2[[2,3,4,1,2,2]]


array([300, 400, 500, 200, 300, 300])

In [84]:
m1 = np.arange(9).reshape((3,3))
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
m1[[0,0,1],[0,1,2]]

array([0, 1, 5])

In [86]:
m1 = np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
m1[:5]

array([0, 1, 2, 3, 4])

In [88]:
m1 = np.array([[0,  1,  2,  3],
               [4,  5,  6,  7],
               [8,  9, 10, 11]])

In [89]:
m1[0,1:3]

array([1, 2])

--------------------------------------------------------------------------------

Replacing element

In [90]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [91]:
a[4:] = 10

In [92]:
a

array([ 0,  1,  2,  3, 10, 10])

--------------------------------------------------------------------------------

# Facny indexing

In [93]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
a < 6 # mask

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [95]:
a[a<6] 

array([0, 1, 2, 3, 4, 5])

In [96]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10])

In [97]:
# Questions
b = np.arange(6)
mask = (b%2==0)
b[mask] = -1
print(b)


[-1  1 -1  3 -1  5]
